const express=require('express');const fs=require('fs');const path=require('path');const {Telegraf,Markup}=require('telegraf');
const app=express(),PORT=process.env.PORT||10000,TOKEN=process.env.BOT_TOKEN,ADMIN=process.env.ADMIN_CHAT_ID;
if(!TOKEN){console.error('Missing BOT_TOKEN');process.exit(1)}
const bot=new Telegraf(TOKEN),file=path.join(__dirname,'orders.json');app.use(express.json());app.use(express.static(path.join(__dirname,'public')));
const load=()=>{try{return JSON.parse(fs.readFileSync(file,'utf8'))}catch{return[]}};const save=x=>fs.writeFileSync(file,JSON.stringify(x,null,2));const id=()=>{const a=load();return a.length?Math.max(...a.map(x=>x.id))+1:1001};
const menu=()=>Markup.inlineKeyboard([[Markup.button.callback('💎 Diamonds','diamonds'),Markup.button.callback('🎫 Membership','membership')],[Markup.button.callback('📈 Level Up','levelup'),Markup.button.callback('🎟️ Booyah Pass','booyah')],[Markup.button.callback('📦 My Orders','orders'),Markup.button.callback('💰 Payment','payment')],[Markup.button.callback('👨‍💼 Support','support')]]);
bot.start(c=>c.reply('🔥 DAGITOPUP 🇪🇹\n\nWelcome to DAGITOPUP!\n\nChoose what you want to order:\n\n💎 Diamonds\n🎫 Membership\n📈 Level Up\n🎟️ Booyah Pass\n\nOrders are manually fulfilled after payment confirmation.',menu()));
bot.command('menu',c=>c.reply('🏠 DAGITOPUP Main Menu',menu()));
bot.command('myid',c=>c.reply(`Your Telegram chat ID is:\n${c.chat.id}`));
bot.command('payment',c=>c.reply('💰 DAGITOPUP PAYMENT 🇪🇹\n\n📱 Telebirr\n👤 Account Name: Abebaw Adamu\n☎️ Number: 0978454451\n\nAfter paying, place your order through the shop and enter your transaction/reference number.\n\n⚠️ Your order is fulfilled manually after payment confirmation.'));
bot.command('support',c=>c.reply('👨‍💼 DAGITOPUP SUPPORT\n\nSend your order number, Telegram username and payment/reference number.'));
for(const [key,text] of [['diamonds','💎 DIAMONDS\n\nChoose a package in the shop.'],['membership','🎫 MEMBERSHIP\n\nChoose Weekly or Monthly Membership in the shop.'],['levelup','📈 LEVEL UP\n\nChoose your Level Up package in the shop.'],['booyah','🎟️ BOOYAH PASS\n\nChoose your Booyah Pass package in the shop.'],['payment','💰 PAYMENT\n\n📱 Telebirr\n👤 Abebaw Adamu\n☎️ 0978454451\n\nPay first, then submit the transaction/reference number.'],['support','👨‍💼 SUPPORT\n\nSend your order number and explain the problem.']]) bot.action(key,async c=>{await c.answerCbQuery();await c.reply(text)});
bot.action('orders',async c=>{await c.answerCbQuery();const a=load().filter(o=>String(o.telegramId)===String(c.from.id));if(!a.length)return c.reply('📦 You have no orders yet.');c.reply('📦 YOUR ORDERS\n\n'+a.slice(-10).reverse().map(o=>`#${o.id} • ${o.product}\n💰 ${o.price} ETB\n💳 ${o.paymentRef}\n📌 ${o.status}`).join('\n\n'))});
app.post('/api/order',async(req,res)=>{try{const {telegramId,username,product,price,uid,paymentRef}=req.body||{};if(!product||!uid||!paymentRef)return res.status(400).json({ok:false,message:'Product, UID and payment reference are required.'});const o={id:id(),createdAt:new Date().toISOString(),telegramId:telegramId||'unknown',username:username||'unknown',product,price:Number(price)||0,uid,paymentRef,status:'WAITING FOR PAYMENT CONFIRMATION'};const a=load();a.push(o);save(a);if(ADMIN)await bot.telegram.sendMessage(ADMIN,`🆕 NEW DAGITOPUP ORDER\n\n🧾 Order: #${o.id}\n📦 Product: ${o.product}\n💰 Price: ${o.price} ETB\n🎮 UID: ${o.uid}\n👤 Customer: @${o.username}\n💳 Payment Ref: ${o.paymentRef}\n\n📌 ${o.status}\n\n/paid ${o.id}\n/complete ${o.id}`);res.json({ok:true,orderId:o.id})}catch(e){console.error(e);res.status(500).json({ok:false,message:'Server error'})}});
async function status(c,n,s){if(!ADMIN||String(c.chat.id)!==String(ADMIN))return c.reply('⛔ Admin only.');const a=load(),o=a.find(x=>String(x.id)===String(n));if(!o)return c.reply('Order not found.');o.status=s;o.updatedAt=new Date().toISOString();save(a);if(o.telegramId!=='unknown')await bot.telegram.sendMessage(o.telegramId,`📦 DAGITOPUP ORDER #${o.id}\n\nStatus: ${s}\nProduct: ${o.product}`);c.reply(`✅ Order #${n}: ${s}`)}
bot.command('paid',c=>status(c,c.message.text.split(' ')[1],'PAYMENT CONFIRMED'));bot.command('complete',c=>status(c,c.message.text.split(' ')[1],'COMPLETED'));
app.get('/health',(q,r)=>r.json({ok:true,service:'DAGITOPUP'}));app.listen(PORT,'0.0.0.0',()=>console.log('DAGITOPUP web app on '+PORT));bot.launch().then(()=>console.log('Bot started'));process.once('SIGINT',()=>bot.stop('SIGINT'));process.once('SIGTERM',()=>bot.stop('SIGTERM'));
